language: java
jdk:
- oraclejdk8
install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true
# script
script: mvn -DskipTests=true clean package
notification:
  email:
    recipients:
    - jiangyj0561@outlook.com
    on_success: always
    on_failure: always
before_script:
- echo "MAVEN_OPTS='-Xms1024m -Xmx2048m -XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=384m'" > ~/.mavenrc
branches:
  only:
  - master
env:
  global:
  - MAVEN_OPTS=-Xms1024m -Xmx2048m -XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=384m
cache:
  directories:
  - $HOME/.m2