mybatis:
  mapper-locations: classpath:/mybatis-mapper/*Mapper.xml
server:
  context-path: /xxl-job-admin
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: root_pwd
    tomcat:
      max-active: 30
      max-wait: 10000
      test-on-borrow: true
    type: org.apache.tomcat.jdbc.pool.DataSource
    url: jdbc:mysql://127.0.0.1:3306/xxl-job?Unicode=true&characterEncoding=UTF-8
    username: root
  freemarker:
    charset: UTF-8
    request-context-attribute: request
    settings:
      number_format: 0.##########
    suffix: .ftl
    templateLoaderPath: classpath:/templates/
  mail:
    host: smtp.qq.com
    password: xxx
    port: 25
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    username: xxx@qq.com
  mvc:
    static-path-pattern: /static/**
  resources:
    static-locations: classpath:/static/
xxl:
  job:
    accessToken: ''
    i18n: ''
    login:
      password: 123456
      username: admin
